### PR TITLE
Create 2022-08-09-venn-diagramming-vendia-share.md

### PR DESCRIPTION
**Pull request by caroll-vendia**
New post (and add images).

### CODE REVIEW

**Comment by caroll-vendia** [comment]
Three_legFigure01

**Comment by caroll-vendia** [comment]
Vendia Architecture drawing with nodes and consensus protocol.

**Comment by alexa-vendia** [comment]
An illustration showing how Vendia's data model is used to generate data storage, file storage, APIs, data-model aware consens and replication layer.)

**Comment by alexa-vendia** [comment]
An illustration showing how multiple parties can share records across time, accumulating a shared set of records and a real-time single source of truth with Vendia Share.

**Comment by alexa-vendia** [comment]
A table showing the potential for matched customer information based on data fields and real-time data sharing permissions in a multi-party data alliance

**Comment by alexa-vendia** [comment]
A table showing the potential for matching logic when multiple parties are sharing data and data fields

**Comment by alexa-vendia** [comment]
Another table showing the potential for matching data in data fields across companies and clouds

**Pull request merged**
